import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import theme from "@/lib/theme";
import { Parkinsans } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const parkinsans = Parkinsans( {
  subsets: [ 'latin' ],
  weight: [ '600', '700', '800' ],
  variable: '--font-parkinsans',
} )

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en" className={ parkinsans.className } >
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={ theme }>
            { children }
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
