import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import theme from "@/lib/theme";
import GlobalSpeedDial from "@/components/lowLevelComponent/SpeedDial";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en"  >
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={ theme }>
            <GlobalSpeedDial />
            { children }
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
