const colors = {
  CeladonPorcelain: "#E7E7E7",
  White: "#FFFFFF",
  FrenchVanillaSorbet: "#FAE8CD",
  RoastedSesame: "#FFC46B",
  BeeCluster: "#FFAC2F",
  Pearl: "#F8F8F8",
  Black: "#000000",
  CapeHope: "#D7D7D7",
  CrystalCut: "#F7F3ED",
  BneiBrakBay: "#1D4FD8",
  RaspberryLeafGreen: "#0C513F",
  CitrusSplash: "#FFC501",
  KissMeKate: "#E7EEEC",
  ChildofLight: "#EFF3F6",
  HoneyBird: "#FFD28D",
  MilkyMaize: "#FAD8A1",
  Sugarwinkle: "#FFC9E4",
  OrangeGlow: "#FFE2BC",
  BreezeofGreen: "#D2F9BE",
  Milan: "#FAF496",
  DrWhite: "#FAFAFA",
  Zinnia: "#FCA311",
  YrielYellow: "#FFDB57",
  ChristySmile: "#F9BBC7",
  Babe: "#D97B79",
  LustfulWishes: "#D33B95",
  BlueAstro: "#4DA8DA",
  BristolBlue: "#578F8E",
  GloomyPurple: "#7E56DA",
  SmokeAndMirrors: "#F3F5F9",
  CoolBalaclavasAreForever: "#14213D",
  Lotion: "#FEFDFB",
  BeniukonBronze: "#FE7D33",
  AlpineRace: "#274061",
  OrangeQuench: "#FFC05F",
  BitSugar: "#F3F2EC",
  StarWhite: "#EFEEE8",
};

export default colors;
